% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Apr-2026 17:11:08
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('soal_7_forecasting.mat');

C1 = saveVarsMat.C1; % <1x1 function_handle> unsupported class

C2 = saveVarsMat.C2; % <1x1 function_handle> unsupported class

K = 5;

L1_val = saveVarsMat.L1_val; % <1x1 sym> unsupported class

L2_val = saveVarsMat.L2_val; % <1x1 sym> unsupported class

L3_val = saveVarsMat.L3_val; % <1x1 sym> unsupported class

N = 24;

a = 2;

b = 2;

f1 = saveVarsMat.f1; % <1x1 sym> unsupported class

f2 = saveVarsMat.f2; % <1x1 sym> unsupported class

f3 = saveVarsMat.f3; % <1x1 sym> unsupported class

p = 10;

q = 0;

x = saveVarsMat.x; % <1x1 sym> unsupported class

clear saveVarsMat;
