% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Apr-2026 16:14:12
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('soal_3_himpunan_fungsi.mat');

A = [24 26 28 31 34 37 39];

A_union_B = [24 26 27 28 29 31 34 36 37 39 42];

B = [27 29 31 34 36 42];

C = [25 31 34 35 41 44];

C_komplemen = [24 26 27 28 29 30 32 33 36 37 38 39 40 42 43];

K = 5;

N = 24;

U = [24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44];

a = 2;

b = 2;

cek_hasil = saveVarsMat.cek_hasil; % <1x1 sym> unsupported class

f = saveVarsMat.f; % <1x1 sym> unsupported class

f_inv_sym = saveVarsMat.f_inv_sym; % <1x1 sym> unsupported class

gabungan_semua = [24 25 26 27 28 29 31 34 35 36 37 39 41 42 44];

hasil_c_aksen = [24 26 27 28 29 36 37 39 42];

irisan_semua = [31 34];

n_c_aksen = 9;

n_gabungan = 15;

n_irisan = 2;

n_sim_diff = 9;

pendapatan_target = 504;

sim_diff = [24 26 27 28 29 36 37 39 42];

x = saveVarsMat.x; % <1x1 sym> unsupported class

x_solusi = saveVarsMat.x_solusi; % <1x1 sym> unsupported class

y = saveVarsMat.y; % <1x1 sym> unsupported class

clear saveVarsMat;
